# Generated by Django 5.0.4 on 2024-04-20 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='Station_Id')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('famousPlaces', models.CharField(max_length=50, verbose_name='FamousPlaces')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User_ID')),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Disabled', 'Disabled')], max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('time', models.FloatField(verbose_name='Time')),
                ('stationid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_station', to='masark.station', verbose_name='StationID')),
            ],
        ),
    ]
