# Generated by Django 5.0.4 on 2024-04-21 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masark', '0002_famousplace_remove_station_famousplaces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='famous_places',
        ),
        migrations.AddField(
            model_name='famousplace',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_place', to='masark.station'),
        ),
    ]
