# Generated by Django 5.0.4 on 2024-04-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masark', '0003_remove_station_famous_places_famousplace_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(unique=True, verbose_name='Station_Id'),
        ),
    ]
